#!/bin/sh

echo "THIS SCRIPT IS DESTRUCTIVE"
echo "DO YOU WANT TO CONTINUE? (y/n)"
read -r response
if [ "$response" != "y" ]; then
    echo "Exiting.."
    exit 1
fi

git clean -fdX
rm -rfv .git
rm -v "$0"
